from __future__ import annotations

from ..ir import split_binding


def render(ir: dict) -> str:
    gaps, keys = ir["gaps"], ir["keybindings"]
    lines = [
        "# Generated by wm-genconf; review before using.",
        "$mainMod = SUPER",
        f"$terminal = {ir['terminal']}",
        f"$launcher = {ir['launcher']}",
        "",
        "general {",
        f"    gaps_in = {gaps['inner']}",
        f"    gaps_out = {gaps['outer']}",
        f"    border_size = {ir['border_width']}",
        "}",
        "",
    ]
    actions = {
        "terminal": ("exec", "$terminal"),
        "launcher": ("exec", "$launcher"),
        "close_window": ("killactive", ""),
    }
    for name, binding in keys.items():
        modifiers, key = split_binding(binding)
        mods = " ".join(modifiers) or "SUPER"
        dispatcher, argument = actions[name]
        lines.append(f"bind = {mods}, {key}, {dispatcher}" + (f", {argument}" if argument else ""))
    return "\n".join(lines) + "\n"
