from __future__ import annotations

from ..ir import split_binding


def render(ir: dict) -> str:
    gaps, keys = ir["gaps"], ir["keybindings"]
    lines = [
        "# Generated by wm-genconf; review before using.",
        f"gappih={gaps['inner']}",
        f"gappiv={gaps['inner']}",
        f"gappoh={gaps['outer']}",
        f"gappov={gaps['outer']}",
        f"borderpx={ir['border_width']}",
        "",
    ]
    actions = {
        "terminal": ("spawn", ir["terminal"]),
        "launcher": ("spawn", ir["launcher"]),
        "close_window": ("killclient", ""),
    }
    for name, binding in keys.items():
        modifiers, key = split_binding(binding)
        mods = "+".join(modifiers) if modifiers else "SUPER"
        action, argument = actions[name]
        lines.append(f"bind={mods},{key},{action}" + (f",{argument}" if argument else ""))
    return "\n".join(lines) + "\n"
