from __future__ import annotations

from ..ir import split_binding


def _key(binding: str) -> str:
    modifiers, key = split_binding(binding)
    names = {"SUPER": "Mod", "CTRL": "Ctrl", "ALT": "Alt", "SHIFT": "Shift"}
    return "+".join([names.get(mod, mod.title()) for mod in modifiers] + [key])


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(ir: dict) -> str:
    gaps, keys = ir["gaps"], ir["keybindings"]
    actions = {
        "terminal": f"spawn {_quote(ir['terminal'])}",
        "launcher": f"spawn {_quote(ir['launcher'])}",
        "close_window": "close-window",
    }
    lines = [
        "# Generated by wm-genconf; review before using.",
        "layout {",
        f"    gaps {gaps['inner']}",
        f"    border {{ width {ir['border_width']} }}",
        "}",
        "",
        "binds {",
    ]
    for name, binding in keys.items():
        lines.append(f"    {_key(binding)} {{ {actions[name]}; }}")
    lines.append("}")
    return "\n".join(lines) + "\n"
