from __future__ import annotations

from ..ir import split_binding


def _key(binding: str) -> str:
    modifiers, key = split_binding(binding)
    names = {"SUPER": "Mod4", "CTRL": "Ctrl", "ALT": "Mod1", "SHIFT": "Shift"}
    return "+".join([names.get(mod, mod.title()) for mod in modifiers] + [key])


def render(ir: dict) -> str:
    gaps, keys = ir["gaps"], ir["keybindings"]
    actions = {
        "terminal": f"exec {ir['terminal']}",
        "launcher": f"exec {ir['launcher']}",
        "close_window": "kill",
    }
    lines = [
        "# Generated by wm-genconf; review before using.",
        f"set $term {ir['terminal']}",
        f"gaps inner {gaps['inner']}",
        f"gaps outer {gaps['outer']}",
        f"default_border pixel {ir['border_width']}",
        "",
    ]
    for name, binding in keys.items():
        lines.append(f"bindsym {_key(binding)} {actions[name]}")
    return "\n".join(lines) + "\n"
