import json
import subprocess
import sys
from pathlib import Path

import pytest

from wm_genconf.backends import BACKENDS
from wm_genconf.config import ConfigError, load_config
from wm_genconf.ir import normalize

ROOT = Path(__file__).resolve().parents[1]


def test_yaml_example_validates():
    config = load_config(ROOT / "examples" / "wayle.yaml")
    assert config["version"] == 1


def test_toml_example_validates():
    config = load_config(ROOT / "examples" / "wayle.toml")
    assert config["desktop"]["terminal"] == "foot"


def test_ir_has_defaults_and_portable_values():
    ir = normalize(load_config(ROOT / "examples" / "wayle.yaml"))
    assert ir["gaps"] == {"inner": 6, "outer": 10}
    assert ir["keybindings"]["terminal"] == "Super+Return"


@pytest.mark.parametrize("backend", sorted(BACKENDS))
def test_backends_emit_nonempty_text(backend):
    ir = normalize(load_config(ROOT / "examples" / "wayle.yaml"))
    output = BACKENDS[backend](ir)
    assert output.startswith("# Generated by wm-genconf")
    assert output.endswith("\n")


def test_invalid_config_is_rejected(tmp_path):
    path = tmp_path / "bad.yaml"
    path.write_text("version: 1\ndesktop:\n  unknown: true\n", encoding="utf-8")
    with pytest.raises(ConfigError):
        load_config(path)


def test_json_input_supported(tmp_path):
    path = tmp_path / "config.json"
    path.write_text(json.dumps({"version": 1, "desktop": {"terminal": "foot"}}), encoding="utf-8")
    assert load_config(path)["version"] == 1


def test_cli_compile():
    result = subprocess.run(
        [sys.executable, "-m", "wm_genconf", "compile", "examples/wayle.yaml",
         "--backend", "hyprland"],
        cwd=ROOT, text=True, capture_output=True, check=False,
    )
    assert result.returncode == 0, result.stderr
    assert "bind = SUPER, Return, exec, $terminal" in result.stdout
